### ISSUE TITLE
建议增加归档功能

### ISSUE THREAD

**Issue by chevion** [75team/ppt#1]
建议增加一个归档功能，用于存储历史记录，归档功能可以有上限，比如最多可以归档10个，新归档的覆盖老数据。可以防止数据丢失，也可以用于找回某个版本的PPT内容。

**Comment by welefen** [comment]
恩，多谢反馈。后面准备改为下面的策略：

![](https://p5.ssl.qhimg.com/t017dd11e9b246c6404.png)

https://p5.ssl.qhimg.com/t017dd11e9b246c6404.png

针对归档功能，后面准备添加如下的策略：

* 对于 slide_config 详情数据没 **3 分钟** 添加一个副本到 S3 中
* 一个 slide 最多只能有 10 个历史

**Comment by welefen** [comment]
@chevion 已经支持
