### ISSUE TITLE
搜索结果页的时间显示不正确

### ISSUE THREAD

**Issue by lizheming** [75team/ppt#10]
https://ppt.baomitu.com/search?type=ppt&kw=%E5%85%B3%E9%94%AE%E6%B8%B2%E6%9F%93%E8%B7%AF%E5%BE%84 搜索结果页的时间显示不正确，另外建议 ppt 详情页里把时间显示加上

![image](https://user-images.githubusercontent.com/424491/38362793-b2dc2bf0-3904-11e8-859c-9b1d4d62bd35.png)

**Comment by welefen** [comment]
显示时间同 https://github.com/75team/ppt/issues/8

**Comment by welefen** [comment]
搜索页面时间问题已经修复
