### ISSUE TITLE
jsbin怎么插入呢？

### ISSUE THREAD

**Issue by cooper1x** [75team/ppt#102]
![image](https://user-images.githubusercontent.com/9080789/69783641-e334d300-11ee-11ea-999e-b0087453047a.png)
https://ppt.baomitu.com/d/53a0a9aa#/18
就是这个，代码插入只是片段。

**Comment by lizheming** [comment]
插 iframe，然后直接贴 jsbin 的地址即可。

**Comment by cooper1x** [comment]
![image](https://user-images.githubusercontent.com/9080789/69786158-cf8c6b00-11f4-11ea-95cc-9cf3f7eb7be1.png)

**Comment by welefen** [comment]
@cooper1x 用 https://code.h5jun.com/

**Comment by cooper1x** [comment]
@welefen 可以了，谢谢
