### ISSUE TITLE
不能制作有声音的ppt了吗

### ISSUE THREAD

**Issue by jasonzhouu** [75team/ppt#103]
之前访问这个网站的时候ppt是可以带音频的，现在好像没有了，取消这个功能了吗？
之前关注收藏这个网站，就是因为它可以录制音频，在录制演讲的时候非常方便，而传统的方式只能是使用视频录制软件。

**Comment by lizheming** [comment]
你好，录音功能应该是在两年前就给下线了 ，主要是使用频率实在是太低了 😢

**Comment by jasonzhouu** [comment]
好的吧，我个人很喜欢这个功能。
