### ISSUE TITLE
ppt的内容突然减少了

### ISSUE THREAD

**Issue by lifushun21** [75team/ppt#106]
以前做过一个ppt,现在看见好多内容没有，这个是怎么回事，能不能帮忙把内容恢复；花了我好多时间做的内容就这样没有了

**Comment by bingomvm** [comment]
@lifushun21 请说下PPT的展示/演讲页的地址，我们这边看下

**Comment by lifushun21** [comment]
https://ppt.baomitu.com/editor/c3cb4b01#/3
以前我还演讲过，现在看发现是很早的东西，最近的东西缺少了很多东西


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"satanImba"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月17日(星期三) 下午4:51
收件人:&nbsp;"75team/ppt"<ppt@noreply.github.com&gt;;
抄送:&nbsp;"江飒心语缘"<1023820960@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [75team/ppt] ppt的内容突然减少了 (#106)





 
@lifushun21 请说下PPT的展示/演讲页的地址，我们这边看下

**Comment by bingomvm** [comment]
查询历史版本后发现数据库的版本和你现在的版本基本一致。丢失的原因是你在编辑的时候由于PPT中的数据校验失败，你的PPT信息都存储在本地了。去年年中由于有安全问题已经清除了用户本地存储的数据，目前这种清空没有办法恢复数据，如果你换过电脑/显示器可以去以前的机器上找找看。
我们后续会更新下PPT的保存策略，将你这种case的数据同步到历史中，非常抱歉无法帮你恢复你的数据。

**Comment by lifushun21** [comment]
就是这个台电脑，我记得前段时间我看到有，就是最近一段时间没有了。。感觉很可惜，做的每份PPT都是很花时间的。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"satanImba"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月17日(星期三) 晚上6:19
收件人:&nbsp;"75team/ppt"<ppt@noreply.github.com&gt;;
抄送:&nbsp;"江飒心语缘"<1023820960@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [75team/ppt] ppt的内容突然减少了 (#106)





 
查询历史版本后发现数据库的版本和你现在的版本基本一致。丢失的原因是你在编辑的时候由于PPT中的数据校验失败，你的PPT信息都存储在本地了。去年年中由于有安全问题已经清除了用户本地存储的数据，目前这种清空没有办法恢复数据，如果你换过电脑/显示器可以去以前的机器上找找看。
 我们后续会更新下PPT的保存策略，将你这种case的数据同步到历史中，非常抱歉无法帮你恢复你的数据。
