### ISSUE TITLE
我原来的账号无法找回了，无法使用邮箱登录了。我原来是用邮箱登录的

### ISSUE THREAD

**Issue by wuzhefang** [75team/ppt#114]

**Comment by lizheming** [comment]
声享一直都只有社交账号登录的，你是不是用的微博登录？目前 baomitu.com 域名因为备案有问题下线了，临时启用了 ppt.75.team 的域名，不过 OAuth 登录这块微博和QQ登录还有问题。目前 Github 和微信登录都是正常的，如果你之前有绑定过 Github 登录的话可以直接用 Github 登录。如果没有绑定过的话可以 Github 登录一下，然后把新的用户和你之前的用户的用户名发我一下，我人工帮你把账号关联一下。

**Comment by wuzhefang** [comment]
***@***.***
***@***.***
。目前这两个账号还能关联起来么？你看着处理一下就行，我里面的ppt应该也不多，如果实在麻烦不弄也行。😀

Austin Lee ***@***.***> 于2021年3月17日周三 下午9:26写道：

**Comment by lizheming** [comment]
你这邮箱咋都显示 * 号了...要能不处理的话就等着吧，一个月之后会回复正常了

**Comment by lizheming** [comment]
你好目前 baomitu.com 域名备案已经完成，声享服务也回归正常了，你可以按照之前的流程使用，感谢。
