### ISSUE TITLE
网页打不开上面的ppt如何找回

### ISSUE THREAD

**Issue by suoutsky** [75team/ppt#118]
网页打不开上面的ppt如何找回

**Comment by lizheming** [comment]
101.199.97.241 ppt.baomitu.com
可以绑下这个 host 备份下吧

**Comment by liushaohua** [comment]
🙄 验证了下，HTTP ERROR 502，请您辛苦帮忙看下~ @lizheming

**Comment by lizheming** [comment]
@liushaohua 我试了，可以打开，就是证书有点问题，你多试试吧。问题我看不了，我已经换工作了。
