### ISSUE TITLE
添加“笔记“，弹层在可视区外面，看不到

### ISSUE THREAD

**Issue by derek2035** [75team/ppt#12]
添加“笔记“，弹层在可视区外面，看不到.

弹层div的top，left计算的有问题。

**Comment by welefen** [comment]
![image](https://user-images.githubusercontent.com/40935/38450577-1558363a-3a53-11e8-94bd-988e35bd5b6e.png)

是演讲笔记么？ 你那里不是这样的样式么？

**Comment by derek2035** [comment]
点演讲笔记
![qq 20180407130600](https://user-images.githubusercontent.com/2821160/38451571-f00cf1ba-3a64-11e8-8fd7-f4d144ae9aab.png)

点完就是这样，只能看到遮罩，看不到弹框
![qq 20180407130905](https://user-images.githubusercontent.com/2821160/38451573-f0b59338-3a64-11e8-861c-9f95a0911584.png)

控制台修改弹层样式后，出来了。
![qq 20180407130800](https://user-images.githubusercontent.com/2821160/38451572-f06109ee-3a64-11e8-9ccf-aecf0ca06b13.png)

环境：
windows10 + chrome65

**Comment by welefen** [comment]
@cuidingfeng 已经修复，看下是否好了
