### ISSUE TITLE
从外面复制图片，粘贴后，会多出来一个Text对象。

### ISSUE THREAD

**Issue by derek2035** [75team/ppt#13]
从外面复制图片，粘贴后，会多出来一个Text对象。

每粘贴一个图片，就会多出来一个Text框

**Comment by welefen** [comment]
未能复现，请提供相关环境和复现步骤（系统、浏览器等信息）

通过如下的步骤未能复现：

1、访问 https://ppt.baomitu.com/conference

![image](https://user-images.githubusercontent.com/40935/38450613-a3ffce98-3a53-11e8-83f1-09e491873597.png)

2、访问 https://ppt.baomitu.com/editor

![image](https://user-images.githubusercontent.com/40935/38450625-c6865d88-3a53-11e8-9c68-cb422e79e546.png)

未能看到 Text 框

**Comment by derek2035** [comment]
一个空页
![qq 20180407124656](https://user-images.githubusercontent.com/2821160/38451458-cb4546fe-3a62-11e8-92aa-b715bef48c29.png)

在QQ浏览器复制图片
![t0192475fc481d4d3e7](https://user-images.githubusercontent.com/2821160/38451462-cc94b6fc-3a62-11e8-9cf3-aee9fc1dc034.jpg)

在chrome的ppt里ctrl+C粘贴
![qq 20180407125202](https://user-images.githubusercontent.com/2821160/38451459-cb99c9ea-3a62-11e8-9d38-7196ec7cb948.png)

实际粘贴出来2个一样的图片，Text框在最下面，把图片拉开，可以看到。但是在chrome里的网页上复制图片的话，粘贴出来，只有一个图片，Text框也是在最下面
![qq 20180407125232](https://user-images.githubusercontent.com/2821160/38451460-cbece756-3a62-11e8-9847-0fb9889e114a.png)

调整图片时，在任意一个操作块上，只要按下鼠标左键，图片就变成这样了。也没办法等比例缩放。
![qq 20180407125346](https://user-images.githubusercontent.com/2821160/38451461-cc416b32-3a62-11e8-973c-0b2dc0e6dbfe.png)



环境：
windows10 + chrome65.0.3298.4

qq浏览器9.7（13014），内核chromium53.0.2785.104

**Comment by derek2035** [comment]
截屏出来的图片，粘贴后，没有问题。

**Comment by welefen** [comment]
@cuidingfeng 帮忙看下，现在是否还有这个问题

**Comment by derek2035** [comment]
刚看了，现在上面两个问题都没有了。
