### ISSUE TITLE
外面复制图片，粘贴进来，调整大小时，一拖动高度就没有了。

### ISSUE THREAD

**Issue by derek2035** [75team/ppt#14]
外面复制图片，粘贴进来，调整大小时，一拖动高度就没有了。

在网页中的图片上复制，再粘贴，就会有这个问题。

直接截屏后粘贴，没有这个问题。

**Comment by welefen** [comment]
未能复现，同  https://github.com/75team/ppt/issues/13 

如有问题再 #13 中统一处理，该 issue 关闭
