### ISSUE TITLE
自动保存问题？

### ISSUE THREAD

**Issue by chenruifu** [75team/ppt#23]
编辑页面中预览没问题，总的39个页。退出页面重新进入剩9个页面了

后面的怎么找回来，或者有什么补救的措施

**Comment by welefen** [comment]
是刚刚编辑的么？还是以前的？
如果是刚刚编辑的，提供下 slide id

**Comment by chenruifu** [comment]
嗯刚刚编辑的
我是 退出后 分享后  才发现只有9页的 
slide id：f0032931
不知道你说的slide id是不是这个？

**Comment by welefen** [comment]
现在保留了最近 10 次的记录，从记录上看，没有那么多页的：

2018-04-09 17:14:15     - 10
2018-04-09 16:53:53    - 9
2018-04-09 15:22:05     - 9
2018-04-09 15:19:04     - 8
2018-04-09 15:16:01      - 7
2018-04-09 15:12:55     - 6
2018-04-09 15:09:54    - 4
2018-04-09 15:06:06    - 4
2018-04-09 15:01:56    - 6
2018-04-09 14:52:01    - 5

**Comment by welefen** [comment]
@chenruifu ping

**Comment by chenruifu** [comment]
那可能是自动保存在某个节点，就出错了。后面操作的都没保存到....
我同事前天也是，碰到跟我一样的问题。

**Comment by welefen** [comment]
是在同一个电脑下操作的么？

发自我的 iPhone

**Comment by chenruifu** [comment]
会不会是我操作的过程中，又新开了一个窗口在操作，两个窗口冲突...
我觉得这个提示，应该要 终止用户操作，就显示几秒，很容易被忽略掉
可能我之前，就是这么操作后，所以才没的...(记得之前这个提示，是英文的 Server error  )

![tim 20180414112729](https://user-images.githubusercontent.com/19771516/38763860-239a0da2-3fd7-11e8-9770-35dfa2f76063.png)

**Comment by welefen** [comment]
现在是有版本号校验的，没通过的话是提示错误的。理论上不会出现覆盖了。

现在已经保存五十个版本了，你下次要还是遇到这个问题到时候再查下。

发自我的 iPhone

**Comment by welefen** [comment]
@chenruifu 这几天还有出现这个提示么？

**Comment by chenruifu** [comment]
貌似正常了，不过最近也用的少...

**Comment by welefen** [comment]
@chenruifu 好的，那先关闭这个 issue，后续再遇到问题，麻烦提个新的 issue
