### ISSUE TITLE
优化导出 PDF 页面效果

### ISSUE THREAD

**Issue by welefen** [75team/ppt#51]
目前有 3 个问题：

* 背景图不能正常展现
* 动画没能显示
* iframe 嵌入打印问题

**Comment by lizheming** [comment]
目前该问题已经使用 puppeteer 方案解决，但是还有一些遗留问题需要修改：
1. 发送邮箱使用用户设置中的邮箱，如若没有设置邮箱则提示用户未绑定邮箱无法使用该功能
2. iframe 导出增加 iframe 地址显示（浮动在 iframe 显示区域的右下角）
3. emoji 需要兼容处理

另外，以下是文章整理大纲 @bingomvm 

------
# 使用 Pupeteer 导出声享 PPT
## 现状
1. 声享是什么？
2. 目前的导出 PDF 访问是什么？
3. 问题有哪些？
    使用 <kbd>⌘</kbd>+<kbd>P</kbd> 导出模式除了有以上几个问题之外还有需要用户手动操作提高了使用难度。
## puppeteer
1. puppeteer 是什么？
2. 为什么选择它？
3. 最后的方案是什么？（提供间断的示例代码）
## 开发中需要注意的问题
0. 异步问题
1. 权限问题
2. iframe 等待问题
3. ....
## 总结
