### ISSUE TITLE
想要 Keynote 乔布斯渐变蓝模板

### ISSUE THREAD

**Issue by chunpu** [75team/ppt#57]
纯黑色在投影上效果不佳, 声享默认的蓝色太淡了, 如果用白色字体还是不突出

目前效果最好的还是乔布斯渐变蓝模板, 上深下浅, 非常需要

![image](https://user-images.githubusercontent.com/4565306/39863771-2cc37a8c-547a-11e8-837c-6bfec0eea213.png)

**Comment by welefen** [comment]
@chunpu  已添加该风格，另外附带赠送了 2 套风格

![](https://p0.ssl.qhimg.com/t01e559a80b5323a805.png)
