### ISSUE TITLE
强烈要求给出“可以画空心带边框的矩形”的功能

### ISSUE THREAD

**Issue by railsbug** [75team/ppt#59]
现在是可以画实体圆圈和实体方块
但是没有“空心只带边框矩形”
这对于制作ppt的人来说 其实还是蛮痛苦的 有时候是需要重点标注的
希望解决一下o(*￣︶￣*)o
顺便说一下 这个应用做的很不错~！

**Comment by welefen** [comment]
@railsbug 恩，我们也意识到了这个问题，会尽快支持下这个功能

**Comment by welefen** [comment]
@railsbug 已经上线，欢迎体验

**Comment by welefen** [comment]
![](https://p4.ssl.qhimg.com/t0132a11ae99b5bba0a.png)
