### ISSUE TITLE
演讲者模式无法再次全屏

### ISSUE THREAD

**Issue by chunpu** [75team/ppt#62]
在演讲者模式里面, 如果点击外链, 或者退出全屏后, 无法再通过点击鼠标进入全屏模式

比如 https://ppt.baomitu.com/p/83d17fc9 页面, 除了一开始可以勾选全屏外, 其他时候无法通过鼠标再次全屏

https://ppt.baomitu.com/d/83d17fc9 这样的链接可以全屏, 但演讲者模式不用这个链接

**Comment by lizheming** [comment]
浏览器自带的全屏快捷键考虑一下？Mac 是 <kbd>control</kbd> + <kbd>⌘</kbd> + <kbd>F</kbd>

**Comment by chunpu** [comment]
@lizheming 是产品让我提的哈哈, 产品和后端对全屏快捷键不是很熟悉, 更喜欢鼠标点击

**Comment by lizheming** [comment]
嗯，先暂时这么用着吧 😄

**Comment by lizheming** [comment]
今天发现原来之前已经做了这个功能了，鼠标移动到左侧边缘后会出现如图的右箭头按钮，点击后会重新唤起初始的左侧配置菜单，可以重新选择全屏。

![image](https://user-images.githubusercontent.com/424491/52929291-ca091700-337e-11e9-8cdb-7fe67b26235a.png)
