### ISSUE TITLE
可否单独设计一个个人主页用于分享或者公开

### ISSUE THREAD

**Issue by shiiiiiiji** [75team/ppt#66]
1、个人Slides主页，可以放在博客里。现在的个人主页看起来很常规，可否设计一套单独可分享的个人主页的页面；
2、有个UI问题：
![image](https://user-images.githubusercontent.com/3774016/42853545-a975bdea-8a69-11e8-82ba-99627263bede.png)

**Comment by lizheming** [comment]
请问你的浏览器是？我在 Mac Safari, Chrome, Firefox 没有复现那个 UI 问题，看起来很诡异…

**Comment by shiiiiiiji** [comment]
@lizheming Chrome，版本号：版本 67.0.3396.99（正式版本） （64 位）

**Comment by lizheming** [comment]
唔...我和你的版本是一样的 -.-||| 你要不进隐私模式看看？
![image](https://user-images.githubusercontent.com/424491/42871362-c51f8812-8aac-11e8-9464-08a82014c58d.png)

**Comment by shiiiiiiji** [comment]
诡异的bug

正常模式：
![tim 20180719084316](https://user-images.githubusercontent.com/3774016/42914998-e886b5ea-8b2f-11e8-95f5-b59de05aba74.png)

隐私模式：
![tim 20180719084339](https://user-images.githubusercontent.com/3774016/42915023-fe98bc5c-8b2f-11e8-9e0e-017b73665e13.png)

**Comment by lizheming** [comment]
😓汗，看了编译后的代码才看到。不知道为什么代码里混入了一个奇怪的 `\b` 字符...已删掉上线了你再看看~

**Comment by shiiiiiiji** [comment]
@lizheming 嗯嗯，没有了，哈哈。不知道明不明白我提的那个需求（哈哈）

**Comment by lizheming** [comment]
明白，我觉得目前的样式 iframe 内嵌也还挺好看的。如果不满意，可以简单的给你包个接口，你自己拿数据渲染就好了。

**Comment by welefen** [comment]
可以加个参数，把顶部的隐藏

**Comment by bingomvm** [comment]
> 可以加个参数，把顶部的隐藏

已增加noHeader参数来控制顶部的显示/隐藏

**Comment by shiiiiiiji** [comment]
> > 可以加个参数，把顶部的隐藏
> 
> 已增加noHeader参数来控制顶部的显示/隐藏

赞👍

**Comment by shiiiiiiji** [comment]
https://ppt.baomitu.com/u/shiji?noHeader=1
