### ISSUE TITLE
我的声享ppt内容看不全了，只剩下前7章咋回事，之前还能全都看到呢

### ISSUE THREAD

**Issue by dandelion1000** [75team/ppt#74]
Slide 地址：https://ppt.baomitu.com/d/a93a144a
最近8月20日的数据是正常的

**Comment by lizheming** [comment]
- [x] 将编辑界面的报错提示显示时长加长
- [x] 增加文本编辑状态粘贴内容的时候过滤掉 HTML 逻辑

**Comment by lizheming** [comment]
assign to @bingomvm
