### ISSUE TITLE
无法导出

### ISSUE THREAD

**Issue by moricabb** [75team/ppt#77]
{"errno":500,"errmsg":"stderr maxBuffer exceeded"}

**Comment by HaveYuan** [comment]
{"errno":500,"errmsg":"stderr maxBuffer exceeded"}

**Comment by bingomvm** [comment]
你好，由于最近添加了很多自定义字体。在导出PPT的时候会将所有字体一同下载，导致生成的zip文件过大，接口失败。我们会尽快解决这个问题，预计这周末恢复正常。谢谢反馈～

**Comment by bingomvm** [comment]
@moricabb @HaveYuan 已修复导出功能。目前导出的本地文件暂不支持文本的自定义字体，这项功能会尽快添加～
