### ISSUE TITLE
哪里可以找到历史记录

### ISSUE THREAD

**Issue by ww1129** [75team/ppt#78]
突然写的十几页ppt没有了，从哪里可以找回？

**Comment by lizheming** [comment]
提供一下PPT地址以及你的联系方式，我们看一下后续联系你。

**Comment by ww1129** [comment]
地址：https://ppt.baomitu.com/editor/fbab0942
1242949804@qq.com 邮箱

**Comment by ww1129** [comment]
ppt丢了后，又随便操作了几次，也把权限改成了私有，数据中应该会有之前的记录吧。。。

**Comment by bingomvm** [comment]
@ww1129 ，问题出现的原因是线上和本地的版本号不匹配导致更新出错。这种情况没有保存ppt数据，后续我们会加上。一般在多电脑或多浏览器同时操作同一ppt会有这个问题，请问你还能回想起出问题时的操作吗？能的话请说下我们排查下问题。

**Comment by ww1129** [comment]
先是在笔记本上有操作，后来换成的台式机，操作写了几张ppt，在切换章节的时候就被清空了。。。
