### ISSUE TITLE
可以支持在一个 ppt 项目里边选中几张剪切到另一个 ppt 项目里吗？ 就是类似 python 的切片那样

### ISSUE THREAD

**Issue by gkfnf** [75team/ppt#83]

**Comment by lizheming** [comment]
按住 Ctrl 键试试，现在就是支持的。

**Comment by gkfnf** [comment]
老哥，我还有一个问题，就是在鼠标滚动页面的时候，在从 PPT 的那个 iframe 那里滚出或者滚进的时候，会发生导航栏会跳，或者说闪烁的问题。我看了一下，在你的博客也存在这个问题，而且似乎通过 iframe 加载别的比如说运行代码之类的也会闪，这个不知道是什么原因引起的呢？

**Comment by gkfnf** [comment]
还有就是，静态博客在手机上似乎很难做到适配，特别是像我的小屏的 iphonese 这种，像我自己的博客，在我手机的 safari 上打开的时候就感觉整个布局就糊掉了。如果按我的使用感受来说的话，手机上打开老哥你的博客也是糊掉了的感觉。特别是因为有些图片或者表格大于页面设定的文本的宽度的时候，它就可以朝右边滑过去，整个排版就一种稀碎的感觉。也是因为这个问题，我一直不知道该怎么在我的博客里把章节目录很好的显示。如何才能在一个小屏的手机上很好的实现一个目录呢？
我看了很多 hugo 的主题，基本都没有目录在手机上显示得好的，然后我天天刷呀刷，找到过一个叫 docsify 的文档项目，像它这种点一个图标把目录切出来然后页面往右边滚过去一点的设计我觉得就很好，但是在小屏的手机上还是会错位。我也不是搞前端的，就了解了一下基本的语法，css 的一些属性之类的都是靠谷歌的，js 也只有一点粗浅的了解，不知道这个问题我应该谷歌什么，学习什么才能解决呢？老哥有没有什么建议？

**Comment by lizheming** [comment]
issue 的问题解决了没有？后续补充的有哪几个问题？请重新整理下措辞描述清楚，我看着有点晕。

**Comment by gkfnf** [comment]
issue 的问题解决了

后续补充的问题：

- 网页浏览的时候，滚动页面，鼠标位置进入 声响PPT界面 的矩形区和滚动脱离的时候，会因为鼠标滚动事件的处理干扰到网页上的导航条的显示位置，也就是所谓的会很快的闪一下。
- 然后是在 iphonese 这类小屏幕手机上无法点开全屏

PS:
如果你是产品经理的话，这些问题就当我没说。
如果你是写代码的老哥，另外一个问题是：
- 如何做一个类似 docsify 这种的目录集成到自己的博客里边，并且能很好的显示在小屏手机上

**Comment by lizheming** [comment]
1. 这块还是买看懂，能帮忙录个视频或者 GIF 么？谢谢
2. 目前使用的 JS 全屏 API 在 iOS 上不支持，所以无法全屏。
3. PPT 不太好生成目录
