### ISSUE TITLE
代码组件编辑换行没有保留

### ISSUE THREAD

**Issue by ryancui92** [75team/ppt#84]
一个小 Bug~

重现步骤：

1. 新建一个代码框，依次按键：`Tab` => `a` => `Enter` => `Backspace` => `Backspace` => `b`，保存。结果如图

![image](https://user-images.githubusercontent.com/3788103/54252878-8b363d80-4587-11e9-8908-1893f11301ed.png)

2. 再次编辑代码，光标定位到第一行行末，按 `Enter`，保存

#### 预期
a 与 b 中间有一空行
#### 实际
a 与 b 中间没有空行

浏览器：Chrome 72.0.3626.121
系统：macOS Mojave

**Comment by lizheming** [comment]
没有复现你的问题，有问题的 PPT 地址没，你发一下，我们看看。

**Comment by ryancui92** [comment]
直接发 editor 地址么？

https://ppt.baomitu.com/editor/6b8360c9#/16

**Comment by NimitzDEV** [comment]
@ryancui- 你好，问题已经修复了，重试一下是否还有问题。

**Comment by ryancui92** [comment]
@NimitzDEV 可以了，thx~
