### ISSUE TITLE
收不到邮箱验证？

### ISSUE THREAD

**Issue by yangfan-coder** [75team/ppt#93]
我用的是QQ有限  谷歌浏览器 反复刷新了三次浏览器。
还是收不到邮件，放心我的网没问题

**Comment by lizheming** [comment]
垃圾邮件里看看？

**Comment by yangfan-coder** [comment]
> 垃圾邮件里看看？
没有 我都看过了

**Comment by bingomvm** [comment]
你qq邮箱方便说下吗？我后台看下

**Comment by yangfan-coder** [comment]
> 你qq邮箱方便说下吗？我后台看下

751152972@qq.com

**Comment by bingomvm** [comment]
> > 你qq邮箱方便说下吗？我后台看下
> 
> [751152972@qq.com](mailto:751152972@qq.com)

我在后台和企业邮箱里查看发送都是成功的，先手动帮你处理下吧。

**Comment by yangfan-coder** [comment]
> > > 你qq邮箱方便说下吗？我后台看下
> > 
> > 
> > [751152972@qq.com](mailto:751152972@qq.com)
> 
> 我在后台和企业邮箱里查看发送都是成功的，先手动帮你处理下吧。

好的 但是确实没收到验证码 你们可以在内测的时候 试一下

**Comment by Gfengwei** [comment]
验证码发送成功，邮箱获取不到验证码；853199755@qq.com
