### ISSUE TITLE
收不到邮箱验证码，今日发送验证码次数过多，明天才能在试，但里边我有一个很重要的PPT明天需要演讲

### ISSUE THREAD

**Issue by 2165911773** [75team/ppt#94]

**Comment by 2165911773** [comment]
在线等，急

**Comment by lizheming** [comment]
解决了么，可以去垃圾邮箱里看看有没？如果没有的话提供下 QQ 号明天单独联系下你。

**Comment by 2165911773** [comment]
已经解决了，谢谢------------------ 原始邮件 ------------------
发件人: "Austin Lee"<notifications@github.com>
发送时间: 2019年6月4日(星期二) 晚上10:34
收件人: "75team/ppt"<ppt@noreply.github.com>;
抄送: "2165911773"<2165911773@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [75team/ppt] 收不到邮箱验证码，今日发送验证码次数过多，明天才能在试，但里边我有一个很重要的PPT明天需要演讲 (#94)



解决了么，可以去垃圾邮箱里看看有没？如果没有的话提供下 QQ 号明天单独联系下你。
 
&mdash;

**Comment by lizheming** [comment]
好的
