### ISSUE TITLE
邮箱被占用

### ISSUE THREAD

**Issue by yuu2lee4** [75team/ppt#96]
您的个人信息不全，部分功能使用受限。请先补全邮箱/手机信息  然后填了一个邮箱 ，提示 邮箱被占用

**Comment by lizheming** [comment]
应该是之前的号已经绑了邮箱了吧，提供下邮箱我们帮你查一下对应的登录方式。

**Comment by yuu2lee4** [comment]
yuu2lee4@qq.com

**Comment by lizheming** [comment]
您好，昨天忙别的事情忘记了。今天帮您看了下，原因是原来您用 QQ 登录注册了一个账号，后来用 Github 又新建了一个账号，同时使用账号关联功能把 QQ 登录绑定到了这个新的账号上，之前的账号就被作废了（这个在绑定的时候应该会提示您）。而您的邮箱不巧绑定在之前的账号上所以导致了这个问题。目前我已经帮您把之前账号的邮箱重置了，您现在可以重新使用这个邮箱了。

**Comment by yuu2lee4** [comment]
好的 谢谢，我当时的操作是github登录，然后退出，然后qq登录，不知道为啥qq就和github绑定了

**Comment by lizheming** [comment]
@yuu2lee4 您这个绑定应该是去年9月5号的事情了，很早就绑定了，和现在的操作关系不大哈。
