### ISSUE TITLE
手机号为什么不能解绑？

### ISSUE THREAD

**Issue by savoygu** [75team/ppt#97]
不小心把手机号绑错了账号，导致有 PPT 的账号没办法绑定手机号，我又没有多个手机号，我应该怎么办？

**Comment by lizheming** [comment]
是不同的社交账号注册的么？如果是的话可以直接绑定对应的社交账号，这样可以把两个账号合并为一个账号把资料转移过来。

**Comment by savoygu** [comment]
好的，我试下

**Comment by savoygu** [comment]
解决了，谢谢💟

**Comment by lizheming** [comment]
不客气~
